# Dnero ETH-RPC Adaptor Configuration
dnero:
  rpcEndpoint: "http://127.0.0.1:15511/rpc"
node:
  skipInitializeTestWallets: true
rpc:
  enabled: true
  httpAddress: "0.0.0.0"
  httpPort: 15444
  wsAddress: "0.0.0.0"
  wsPort: 15445
  timeoutSecs: 600 
  maxConnections: 2048
log:
  levels: "*:info"